site_name: My Docs
theme:
  name: material

extra_css:
  # - styles/timeline.scss
  - styles/neoteroi-mkdocs.css

markdown_extensions:
  - neoteroi.timeline
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg